services:
  budget-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: budget-app
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_PATH=/app/data/budget.db
    volumes:
      # Mount volume to persist database
      - budget-data:/app/data
    restart: unless-stopped

volumes:
  budget-data:
    driver: local
